apiVersion: v1
kind: Service
metadata:
  name: my-backend-service # very very important -nginx proxypass needs this name
  labels:
    app: my-backend-svc
spec:
  #type: ClusterIP # ClusterIP is default service in Kubernetes
  selector:
    app: backend-restapp
  ports:
    - name: http # Service Port Name
      port: 8080 # Cluster IP Service Port
      targetPort: 8080 # Container Port
