apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend-deployment-nginx
  labels:
    app: my-frontend-nginx-app
    tier: frontend
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: my-frontend-nginx
  template:
    metadata:
      name: my-frontend-pod-nginx
      labels:
        app: my-frontend-nginx
        tier: frontend
    spec:
      containers:
        - name: my-frontend-container
          image: stacksimplify/kube-frontend-nginx:1.0.0
          ports:
            - containerPort: 80
