apiVersion: v1
kind: Service
metadata: # Dictionary
  name: my-frontend-svc-loadbalancer
spec: # Dictionary
  type: LoadBalancer #
  selector: # Dictionary
    app: my-frontend-nginx
  ports: # List
    - name: http
      port: 80
      targetPort: 80
