apiVersion: v1
kind: Service
metadata:
  name: myservice-app-loadbalancer
spec:
  type: LoadBalancer # kubernetes service type ex: ClusterIP, NodePort etc.
  selector: # Backend pool for load balancer, where to route the traffic. what is the backend for this service.
    app: myapp # this is comming from Pod Yaml file as we define the label app: myapp when creating the Pod.
  ports:
    - name: http # 
      port: 80 # Service Port
      targetPort: 80 # Container Port, in this case out container is holding nginx web server which is using port 80
