apiVersion: v1 # string
kind: Service # String
metadata: # Dictionary
  name: myapp3-deployment-lb-service # Key Value
spec: # Dictionaru
  type: LoadBalancer #ClusterIP, # NodePort
  selector:
    app: myapp3 # Key Valur
  ports: # List
    - name: http 
      port: 80 # Service Port
      targetPort: 80 # Container Port
