apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector: # Pod Select Label
    matchLabels:
      app: mysql-label
  strategy: # Strategy for our Deployment. Default is rolling update. we are selectin Recreate type because this is Database
    type: Recreate
  template: # Pod Template
    metadata:
      name: mysql-pod
      labels:
        app: mysql-label
    spec: # Pod Specification
      containers:
        - name: mysql-container
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: dbpassword11
          volumeMounts: # Container level resource
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d
          ports:
            - containerPort: 3306
              name: mysql
      volumes: # Pod Spec level resource
        - name: mysql-persistent-storage
          persistentVolumeClaim: 
            claimName: azure-managed-disk-pvc
        - name: usermanagement-dbcreation-script
          configMap:
            name: usermanagement-dbcreation-script
