apiVersion: v1
kind: Service
metadata:
  name: myapp-replica-set-lb-service
spec:
  type: LoadBalancer # ClusterIP, # NodePort
  selector: 
    app: myapp2
  ports:
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
